<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="10" total="13" passed="0" failed="0" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-22T11:38:44 IST" name="Suite" finished-at="2023-12-22T11:38:44 IST" duration-ms="49">
    <groups>
    </groups>
    <test started-at="2023-12-22T11:38:44 IST" name="Test" finished-at="2023-12-22T11:38:44 IST" duration-ms="49">
      <class name="TestScripts.CartTest">
        <test-method is-config="true" signature="startApp()[pri:0, instance:TestScripts.CartTest@121314f7]" started-at="2023-12-22T11:38:44 IST" name="startApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1703225324616" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method is-config="true" signature="login()[pri:0, instance:TestScripts.CartTest@121314f7]" started-at="2023-12-22T11:38:44 IST" name="login" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1703225324618" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="cartmoduletest()[pri:0, instance:TestScripts.CartTest@121314f7]" started-at="2023-12-22T11:38:44 IST" name="cartmoduletest" finished-at="2023-12-22T11:38:44 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.InvalidServerInstanceException">
            <message>
              <![CDATA[The main Appium script does not exist at 'C:\Users\sys\AppData\Roaming\npm\node_modules\appium\build\lib\main.js']]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.InvalidServerInstanceException: The main Appium script does not exist at 'C:\Users\sys\AppData\Roaming\npm\node_modules\appium\build\lib\main.js'
at io.appium.java_client.service.local.AppiumServiceBuilder.validatePath(AppiumServiceBuilder.java:128)
at io.appium.java_client.service.local.AppiumServiceBuilder.loadPathToMainScript(AppiumServiceBuilder.java:291)
at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:358)
at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:57)
at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:463)
at GenericUtilities.BaseClass.startServer(BaseClass.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.InvalidServerInstanceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cartmoduletest -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:TestScripts.CartTest@121314f7]" started-at="2023-12-22T11:38:44 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1703225324623" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- TestScripts.CartTest -->
      <class name="TestScripts.InboxTest">
        <test-method is-config="true" signature="startApp()[pri:0, instance:TestScripts.InboxTest@130c12b7]" started-at="2023-12-22T11:38:44 IST" name="startApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1703225324624" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method is-config="true" signature="login()[pri:0, instance:TestScripts.InboxTest@130c12b7]" started-at="2023-12-22T11:38:44 IST" name="login" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1703225324625" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="tc3()[pri:0, instance:TestScripts.InboxTest@130c12b7]" started-at="2023-12-22T11:38:44 IST" name="tc3" finished-at="2023-12-22T11:38:44 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.InvalidServerInstanceException">
            <message>
              <![CDATA[The main Appium script does not exist at 'C:\Users\sys\AppData\Roaming\npm\node_modules\appium\build\lib\main.js']]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.InvalidServerInstanceException: The main Appium script does not exist at 'C:\Users\sys\AppData\Roaming\npm\node_modules\appium\build\lib\main.js'
at io.appium.java_client.service.local.AppiumServiceBuilder.validatePath(AppiumServiceBuilder.java:128)
at io.appium.java_client.service.local.AppiumServiceBuilder.loadPathToMainScript(AppiumServiceBuilder.java:291)
at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:358)
at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:57)
at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:463)
at GenericUtilities.BaseClass.startServer(BaseClass.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.InvalidServerInstanceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:TestScripts.InboxTest@130c12b7]" started-at="2023-12-22T11:38:44 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1703225324628" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- TestScripts.InboxTest -->
      <class name="TestScripts.FavouriteTest">
        <test-method is-config="true" signature="startServer()[pri:0, instance:TestScripts.FavouriteTest@242b836]" started-at="2023-12-22T11:38:44 IST" name="startServer" finished-at="2023-12-22T11:38:44 IST" duration-ms="49" status="FAIL">
          <exception class="io.appium.java_client.service.local.InvalidServerInstanceException">
            <message>
              <![CDATA[The main Appium script does not exist at 'C:\Users\sys\AppData\Roaming\npm\node_modules\appium\build\lib\main.js']]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.InvalidServerInstanceException: The main Appium script does not exist at 'C:\Users\sys\AppData\Roaming\npm\node_modules\appium\build\lib\main.js'
at io.appium.java_client.service.local.AppiumServiceBuilder.validatePath(AppiumServiceBuilder.java:128)
at io.appium.java_client.service.local.AppiumServiceBuilder.loadPathToMainScript(AppiumServiceBuilder.java:291)
at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:358)
at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:57)
at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:463)
at GenericUtilities.BaseClass.startServer(BaseClass.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.InvalidServerInstanceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startServer -->
        <test-method is-config="true" signature="startApp()[pri:0, instance:TestScripts.FavouriteTest@242b836]" started-at="2023-12-22T11:38:44 IST" name="startApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1703225324599" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method is-config="true" signature="login()[pri:0, instance:TestScripts.FavouriteTest@242b836]" started-at="2023-12-22T11:38:44 IST" name="login" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1703225324609" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="favourite()[pri:0, instance:TestScripts.FavouriteTest@242b836]" started-at="2023-12-22T11:38:44 IST" name="favourite" finished-at="2023-12-22T11:38:44 IST" duration-ms="0" status="SKIP">
          <exception class="io.appium.java_client.service.local.InvalidServerInstanceException">
            <message>
              <![CDATA[The main Appium script does not exist at 'C:\Users\sys\AppData\Roaming\npm\node_modules\appium\build\lib\main.js']]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.InvalidServerInstanceException: The main Appium script does not exist at 'C:\Users\sys\AppData\Roaming\npm\node_modules\appium\build\lib\main.js'
at io.appium.java_client.service.local.AppiumServiceBuilder.validatePath(AppiumServiceBuilder.java:128)
at io.appium.java_client.service.local.AppiumServiceBuilder.loadPathToMainScript(AppiumServiceBuilder.java:291)
at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:358)
at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:57)
at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:463)
at GenericUtilities.BaseClass.startServer(BaseClass.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.InvalidServerInstanceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- favourite -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:TestScripts.FavouriteTest@242b836]" started-at="2023-12-22T11:38:44 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1703225324615" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="stopServer()[pri:0, instance:TestScripts.FavouriteTest@242b836]" started-at="2023-12-22T11:38:44 IST" name="stopServer" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1703225324732" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopServer -->
      </class> <!-- TestScripts.FavouriteTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
